### ISSUE TITLE
You need a Java Runtime Environment to run the Solr server

### ISSUE THREAD

**Issue by Revokee** [sunspot/sunspot#530] opened 2014-01-08 17:48 UTC
I can't start my solr server in production environment anymore I keeping getting the error. After I run

```
rake sunspot:solr:start RAILS_ENV=production
```

I receive

```
You need a Java Runtime Environment to run the Solr server
```

Here is the trace of the command

```
** Invoke sunspot:solr:start (first_time)
** Invoke environment (first_time)
** Execute environment
[deprecated] I18n.enforce_available_locales will default to true in the future. If you really want to skip validation of your locale you can set I18n.enforce_available_locales = false to avoid this message.
** Execute sunspot:solr:start
rake aborted!
You need a Java Runtime Environment to run the Solr server
```

java -version return me the following

```
java version "1.7.0_45"
OpenJDK Runtime Environment (rhel-2.4.3.4.el6_5-x86_64 u45-b15)
OpenJDK 64-Bit Server VM (build 24.45-b08, mixed mode)
```

And 

```
bundle exec rake --execute 'puts `which java`'
```

return

/usr/bin/java

The same results that which java gives

I`m on Solr 4.6, Ruby 2.0, Rails 4.0.0.rc1 and the versions of the gems are

```
* sunspot (2.1.0)
* sunspot_rails (2.1.0)
* sunspot_solr (2.1.0)
```

**Comment by IslamAzab** [comment] 2015-04-15 11:29
@Revokee @DaniG2k I have never faced this issue before, but suddenly it is showing up now!

The problem is with the `$PATH` enviroment variable.

Try checking this output `RAILS_ENV=<some_env> bundle exec rake --execute 'system "echo $PATH"'`

Also check the output of this in your rails console `system "echo $PATH"`

[`Sunspot::Solr::Java.installed?`](https://github.com/sunspot/sunspot/blob/691b42e73beae37e2e05953a1110f4247ec0065c/sunspot_solr/lib/sunspot/solr/server.rb#L201) returns nil due to path problems.

**Comment by DaniG2k** [comment] 2016-03-18 15:59
If I do `Sunspot::Solr::Java.installed?`I am seeing `true`.

I'm not sure what's changed between versions but I am now getting a different error about JAVA_HOME not working properly (even though I triple checked and that's where my java binary lives). The full issue is [outlined here](http://stackoverflow.com/questions/36088497/unable-to-start-sunspot-solr-in-production).

**Comment by DaniG2k** [comment] 2016-03-18 16:22
I think I've identified the problem. The issue in the code is [here](https://github.com/sunspot/sunspot/blob/445a6f199d4bb8ad95d6001ed49d763616aeaed1/sunspot_solr/solr/bin/solr#L111).

If I run the code:

```
for java in "$JAVA_HOME"/bin/amd64/java "$JAVA_HOME"/bin/java; do
  echo $java;
done
```

into the command line, I am seeing:

```
/usr/lib/jvm/java-7-openjdk-amd64/jre/bin/bin/amd64/java
/usr/lib/jvm/java-7-openjdk-amd64/jre/bin/bin/java
```

My Java binary exists in neither of those directories. It lives in

`/usr/lib/jvm/java-7-openjdk-amd64/jre/bin`

There's an extra `/bin` being appended

**Comment by DaniG2k** [comment] 2016-03-18 16:29
Fixed by setting `$JAVA_HOME` to `/usr/lib/jvm/java-7-openjdk-amd64` in /etc/environment. Now getting a different problem -_-

**Comment by sweetleon** [comment] 2017-12-18 04:25
I found that, on a Mac, `which java` yielded `/usr/bin/java` but running `java` showed that it was just a stub for an app that told me to _actually_ install Java. following its instructions solved the problem for me.

**Comment by mlh758** [comment] 2019-05-16 15:27
Closing due to age.

**Closed by mlh758** 2019-05-16 15:27 UTC
Labels: support
