### ISSUE TITLE
Custom schema.xml in Sunspot 2.1.0

### ISSUE THREAD

**Issue by maxtherocket** [sunspot/sunspot#504] opened 2013-11-19 04:02 UTC
After upgrading to Sunspot 2.1.0 from 2.0, my custom schema.xml field types are missing. I am guessing that the new version of Sunspot doesn't use schema.xml from the RAILS_ROOT/solr/config/schema.xml, and instead, uses the schema.xml found in the gem's directory.

Is there a way to configure the new version of the gem to use the schema file found in RAILS_ROOT/solr/config/schema.xml?

**Comment by Irostovsky** [comment] 2015-02-27 12:12
Not worked for me also.
@jaygen, I have tried to set up solr_home with absolute path, but it returns 404. 
When I try to set solr_home: solr, then server is run ok, but it uses gem's schema.xml(without my custom fields)

**Comment by tzhbami7** [comment] 2015-03-11 14:28
Same issue with 2.1.1 :( Any ideas?

**Comment by Irostovsky** [comment] 2015-03-11 16:31
@tzhbami7, for me the following trick had worked: I have renamed solr folder to solr_old and run installer. After it I just added my custom fields to schema.yml in new generated solr folder and it works for now.
Hope this help you!

**Comment by backus** [comment] 2015-03-11 21:37
:+1: on @Irostovsky's solution.  Worked for me.

**Comment by Irostovsky** [comment] 2015-03-12 07:14
Looks like it is not solr issue, but it is needed to add little migration guide :)

**Comment by tzhbami7** [comment] 2015-03-12 08:17
mhh - will check that out @Irostovsky

**Comment by tzhbami7** [comment] 2015-03-12 09:16
@Irostovsky it worked - yay :) thx! You saved my day

**Comment by jvenezia** [comment] 2015-05-07 08:57
Same problem here. @Irostovsky 's solution worked. But the problem is that the gem won't generate the solr files if there is already a solr directory. My solr directory contained only the schema.xml file, and at the first solr start, the others files were not generated in this directory.

So it only works if the solr directory does not exist. And you have to move the schema.xml file after the first run.

This is an issue according to me.

**Comment by mlh758** [comment] 2019-05-16 14:16
Closing this due to age. The built in solr should only be used for development purposes.

**Closed by mlh758** 2019-05-16 14:16 UTC
Labels: support
