### ISSUE TITLE
order_by on integer

### ISSUE THREAD

**Issue by noiseunion** [sunspot/sunspot#643] opened 2014-12-12 16:18 UTC
I am trying to sort my results using an integer field.  Unfortunately, the order by appears to be getting completely ignored and things are coming back all jumbled.  Is there something special that needs to be done to order_by an integer?

I found this [work around](http://stackoverflow.com/questions/25092827/sunspot-solr-order-by-integer-value-completely-broken) that may have to use for now.

**Comment by mwysinski** [comment] 2015-03-20 08:24
+1

**Comment by brandonjmckay** [comment] 2015-03-25 23:29
+1

**Comment by Adam-Randall** [comment] 2016-05-10 10:45
+1

**Comment by abrambailey** [comment] 2016-08-05 21:27
+1

**Comment by abrambailey** [comment] 2016-08-05 21:28
I had the same problem ordering a float. Not sure what's going on.

**Comment by sagarbommidi** [comment] 2016-08-09 12:37
I tried to reproduce the same issue, but its working as expected without any errors.

I have a `Show` model, and it has an integer field `reservation_valid_for`. And `shows` table has few records.

Model code is:

```ruby
searchable do
  integer :id
  integer :reservation_valid_for, stored: true
  string :banner_url
  #.... etc
end
```

Initially, i have tried to get the results without providing any order_by. Then the values are not sorted as shown in the below image.

![Results without any Sorting applied](https://lh6.googleusercontent.com/bGaySN1JHo6GcWJepfppxkEN_SsjXekMfa3b8SltyZXyCLAtzfoKdlENUPBGmkcBnQ1x_e3V=w2878-h1476-rw)

Now i have added the order_by class, and checked that the results are coming properly.

Code for search is:

```ruby
Show.search do
  without(:banner_url, nil)
  order_by :reservation_valid_for, :asc
end
```

![Results with Sorting applied](https://lh4.googleusercontent.com/NH50K3YSCh7oIClWNQ9IkU2Q_r6MNVkXA9aMZc1lWQWLwNCwtJJrXoQZdVyyl8E_7GLNFhQe=w2878-h1476-rw)

In the above image, the results are sorted in `asc` order, and the search is working properly for `desc` order also.

**PS:** _Before re-indexing, the values are not sorting properly. But once after i did re-indexing, sorting is working without any issues_.

**Comment by abrambailey** [comment] 2016-08-09 14:30
@sagarbommidi I'm wondering if this may be an issue with my dev environment. It seems that reindexing isn't fixing my issues locally, but that sorting by integers is still working in production. 

Local:
```

solr-spec
4.2.0.2013.03.06.22.32.13
solr-impl
4.2.0 1453694 - rmuir - 2013-03-06 22:32:13
lucene-spec
4.2.0
lucene-impl
4.2.0 1453694 - rmuir - 2013-03-06 22:25:29
```
Unfortunately I can't find the version we are using in production right now.

**Comment by bragboy** [comment] 2016-08-16 11:16
As @sagarbommidi explained that we need to index on integer fields, before using order_by on it, I am closing it.

**Closed by bragboy** 2016-08-16 11:16 UTC

**Comment by abrambailey** [comment] 2016-08-16 12:44
Thanks. For whatever reason this is not working for me locally after reindexing... So my issue is still an issue.

**Comment by antonyr** [comment] 2016-08-16 15:12
Hi @abrambailey 
Could you please make the query and view the results through Solr UI and let us know if UI is returning the expected results and Sunspot is not

**Comment by abrambailey** [comment] 2016-08-16 15:39
Seems to be working just fine in SOLR admin
![image](https://cloud.githubusercontent.com/assets/978462/17705346/a3e31d04-639d-11e6-8e59-302f17e4809c.png)

**Comment by abrambailey** [comment] 2016-08-16 15:39
When I sort by `score desc` it does not work. I have to use `score_is`

**Comment by abrambailey** [comment] 2016-08-16 15:42
Definitely working:
```
<?xml version="1.0" encoding="UTF-8"?>
<response>

<lst name="responseHeader">
  <int name="status">0</int>
  <int name="QTime">1</int>
</lst>
<result name="response" numFound="5337" start="0">
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">99</int></doc>
  <doc>
    <int name="score_is">97</int></doc>
  <doc>
    <int name="score_is">97</int></doc>
  <doc>
    <int name="score_is">96</int></doc>
  <doc>
    <int name="score_is">96</int></doc>
  <doc>
    <int name="score_is">96</int></doc>
  <doc>
    <int name="score_is">95</int></doc>
  <doc>
    <int name="score_is">95</int></doc>
  <doc>
    <int name="score_is">93</int></doc>
  <doc>
    <int name="score_is">93</int></doc>
  <doc>
    <int name="score_is">91</int></doc>
  <doc>
    <int name="score_is">91</int></doc>
  <doc>
    <int name="score_is">91</int></doc>
  <doc>
    <int name="score_is">91</int></doc>
  <doc>
    <int name="score_is">91</int></doc>
  <doc>
    <int name="score_is">91</int></doc>
  <doc>
    <int name="score_is">91</int></doc>
  <doc>
    <int name="score_is">91</int></doc>
  <doc>
    <int name="score_is">90</int></doc>
  <doc>
    <int name="score_is">87</int></doc>
  <doc>
    <int name="score_is">65</int></doc>
  <doc>
    <int name="score_is">25</int></doc>
  <doc>
    <int name="score_is">16</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
</result>
</response>
```

**Comment by abrambailey** [comment] 2016-08-16 15:43
Results from `score desc`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<response>

<lst name="responseHeader">
  <int name="status">0</int>
  <int name="QTime">0</int>
</lst>
<result name="response" numFound="5337" start="0">
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">100</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
  <doc>
    <int name="score_is">0</int></doc>
</result>
</response>
```

**Comment by abrambailey** [comment] 2016-08-16 15:45
By the way I changed my searchable block slightly to store the score as follows
```ruby
    integer :score, stored: true do
      score || 0
    end
```

**Comment by abrambailey** [comment] 2016-08-16 15:50
Just confirmed that sorting by `score_to_time_d` also works just fine in SOLR.
