### ISSUE TITLE
 sunspot_rails:install generator fails with 'Could not find generator' error

### ISSUE THREAD

**Issue by ThePraveen** [sunspot/sunspot#836] opened 2016-12-16 13:57 UTC
Rails 5.0.0.1
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]

$ rails generate sunspot_rails:install  
is failing with error:-
Could not find generator 'sunspot_rails:install'. Maybe you meant 'responders:install', 'audited:install' or 'apipie:install'

**Comment by garbo999** [comment] 2016-12-19 13:24
Since no one else has responded, I will ask:
- Did you add the two gems to the Gemfile and run `bundle install`?
- Could it be that Sunspot is not compatible with Rails 5? README.md only mentions `Quickstart with Rails 3 / 4`.

**Comment by ThePraveen** [comment] 2016-12-19 14:38
1. Yes both the gems are present and bundle install was successful.
2. Can anyone confirm that sunspot is not compatible wth rails 5?

**Comment by ThePraveen** [comment] 2016-12-20 12:36
Anyone?

**Comment by mlh758** [comment] 2019-07-30 19:32
Closing this due to age.

**Closed by mlh758** 2019-07-30 19:32 UTC

**Comment by kevr** [comment] 2019-11-17 17:30
Why was this closed? The question was never answered.

**Comment by mlh758** [comment] 2019-11-18 15:04
I closed it because it was a 3 year old issue that was asking for help with setup, not a bug report or feature request that we are going to implement a change for. It also doesn't appear to be wide spread so there wouldn't be a lot of value trying to restart this conversation.

**Comment by kevr** [comment] 2019-11-24 14:42
Alright. I'm not 100% sure if this is the case because I'm quite new to ruby/rails, but this seems to be an issue related to the rails version. I went with another package to search rails objects called SearchObject. May be a solution if folks can't figure out how to get sunspo running above Rails 5.

**Comment by mlh758** [comment] 2019-11-24 15:01
I've been using Sunspot with Rails 5/5.1 for quite some time so I know it's compatible (also works on 6). All the generator does is put [the config file](https://github.com/sunspot/sunspot/blob/master/sunspot_rails/generators/sunspot/templates/sunspot.yml) in your rails root/config directory. If you're having trouble it might be faster to just paste that in there.

**Comment by mlh758** [comment] 2019-11-24 15:10
Also, if you're talking about this [SearchObject](https://github.com/RStankov/SearchObject) that's a very different type of package from this. Sunspot is an interface into Apache Solr which is [all this stuff](https://lucene.apache.org/solr/guide/7_0/overview-of-searching-in-solr.html). You might run into some difficulty matching that capability even if you use SearchObject to wrap the query endpoint.

**Comment by serggl** [comment] 2019-11-24 16:40
`$ rails generate sunspot_rails:install` works just fine for me on Rails 5.2 project
