### ISSUE TITLE
Unable to run any specs

### ISSUE THREAD

**Issue by aomega08** [sunspot/sunspot#645] opened 2014-12-17 17:23 UTC
I am working for a company where we have a very large app with no specs at all. They asked me to design and implement some APIs, and I decided that I want at least that tested. So I runt rspec (the gem was installed, and a few tests actually existed, but the command itself has not been runt for months). The spec actually runt fine (except for a lot of test failures). Since it was RSpec 2.0, I upgraded to RSpec 3.1. Then specs stopped running.

This is the top of the call stack:

```
/Users/f.boffa/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/rspec-mocks-3.1.3/lib/rspec/mocks/argument_matchers.rb:60:in `boolean': wrong number of arguments (1 for 0) (ArgumentError)
    from /Users/f.boffa/Projects/promoqui-server/app/models/city.rb:33:in `block in <class:City>'
    from /Users/f.boffa/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/sunspot-2.0.0/lib/sunspot/util.rb:208:in `instance_eval'
    from /Users/f.boffa/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/sunspot-2.0.0/lib/sunspot/util.rb:208:in `instance_eval_with_context'
    from /Users/f.boffa/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/sunspot-2.0.0/lib/sunspot/util.rb:86:in `instance_eval_or_call'
    from /Users/f.boffa/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/sunspot-2.0.0/lib/sunspot/setup.rb:103:in `setup'
    from /Users/f.boffa/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/sunspot-2.0.0/lib/sunspot/setup.rb:296:in `setup'
    from /Users/f.boffa/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/sunspot-2.0.0/lib/sunspot.rb:166:in `setup'
    from /Users/f.boffa/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/sunspot_rails-2.0.0/lib/sunspot/rails/searchable.rb:81:in `searchable'
    from /Users/f.boffa/Projects/promoqui-server/app/models/city.rb:21:in `<class:City>'
    from /Users/f.boffa/Projects/promoqui-server/app/models/city.rb:1:in `<top (required)>'
    from /Users/f.boffa/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `require'
    from /Users/f.boffa/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `block in require'
    from /Users/f.boffa/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:213:in `load_dependency'
    from /Users/f.boffa/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `require'
    from /Users/f.boffa/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:329:in `require_or_load'
    from /Users/f.boffa/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:462:in `load_missing_constant'
    from /Users/f.boffa/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:183:in `const_missing'
    from /Users/f.boffa/Projects/promoqui-server/spec/factories/city.rb:4:in `block in <top (required)>'
    from /Users/f.boffa/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/factory_girl-4.2.0/lib/factory_girl/syntax/default.rb:49:in `instance_eval'
    from /Users/f.boffa/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/factory_girl-4.2.0/lib/factory_girl/syntax/default.rb:49:in `run'
    from /Users/f.boffa/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/factory_girl-4.2.0/lib/factory_girl/syntax/default.rb:7:in `define'
    from /Users/f.boffa/Projects/promoqui-server/spec/factories/city.rb:3:in `<top (required)>'
    from /Users/f.boffa/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:222:in `load'
    from /Users/f.boffa/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:222:in `block in load'
    from /Users/f.boffa/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:213:in `load_dependency'
    from /Users/f.boffa/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:222:in `load'
    from /Users/f.boffa/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/factory_girl-4.2.0/lib/factory_girl/find_definitions.rb:20:in `block (2 levels) in find_definitions'
```

For what I could understand, FactoryGirl loads all factories, including a particular "City" (whose factory is actually empty). It then loads the City Model. And there is the Sunspot searchable block:

```
class City < ActiveRecord::Base
  [...]

  searchable :auto_index => false, :auto_remove => false do
    text :name, :stored => true
    autosuggest :city_name, :using => :name

    boolean :active
  end
  [...]
end
```

The error claims that boolean is called with the wrong number of arguments. It is actually calling `boolean` from `RSpec::Mocks::ArgumentMatchers`!!

The problem repeats if I remove the city factory, because there are many other factory and models with the same setup.

So why is boolean being sent to rspec and not to sunspot? I hope this is reproducible. If not, I'll try to build a minimal app for you.

rspec (and rspec-mocks) version: 3.1.0
sunspot (and sunspot_rails) version: 2.0.0
ruby: 2.0.0-p247
rails: 4.0.0

**Comment by visitvinoth** [comment] 2016-11-11 07:40
I cannot reproduce this issue now. I believe this should get fixed with https://github.com/rspec/rspec-mocks/issues/845 and https://github.com/zephyr-dev/grape-entity-matchers/commit/655a3af540caaf0a15d5e82ac4f3627c014a4da5.

We can close this issue.

**Closed** 2016-11-11 09:45 UTC
